# App
spring.application.name=notebook-app

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/notebookdb?TimeZone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.username=${SPRING_DATA_REDIS_USERNAME:}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${SPRING_DATA_REDIS_SSL:false}

# auth
# Google OAuth
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:admin123}
spring.rabbitmq.virtual-host=${SPRING_RABBITMQ_VHOST:/}
spring.rabbitmq.ssl.enabled=${SPRING_RABBITMQ_SSL:false}

# Queue config
rabbitmq.queue.execution=execution.queue
rabbitmq.exchange=execution.exchange
rabbitmq.routing.key=execution.routing.key

# redis cache
spring.cache.type=redis
spring.cache.redis.time-to-live=3600000

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Frontend / CORS
app.frontend-url=${FRONTEND_URL:http://localhost:5173}
app.allowed-origins=${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

server.port=${PORT:8080}
